<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/it/modules.php 
 * 
 * Contao extension: gallery_creator 4.0.1 stable 
 * Italienisch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['1'] = "Crea ed edita gallerie di album";
$GLOBALS['TL_LANG']['FMD']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['FMD']['gallery_creator']['1'] = "Presenta album gallery_creator come un modulo frontend.";
$GLOBALS['TL_LANG']['CTE']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['CTE']['gallery_creator']['1'] = "Presenta album gallery_creator come un elemento di contenuto frontend.";
