<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/modules.php 
 * 
 * Contao extension: gallery_creator 3.1.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['1'] = "Bildgalerien erstellen und bearbeiten.";
$GLOBALS['TL_LANG']['FMD']['webgallery']['0'] = "Bildgalerien";
$GLOBALS['TL_LANG']['FMD']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['FMD']['gallery_creator']['1'] = "Album-Bilder des Gallery-Creators als Frontend-Modul anzeigen.";
$GLOBALS['TL_LANG']['CTE']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['CTE']['gallery_creator']['1'] = "Eine Gallerie als Inhaltselement einf&uuml;gen.";
 
?>
