<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/tl_content.php 
 * 
 * Contao extension: gallery_creator 4.1.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['miscellaneous_legend'] = "Allgemeine Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['sorting_legend'] = "Alben-Auflistung-Sortieroptionen";
$GLOBALS['TL_LANG']['tl_content']['picture_sorting_legend'] = "Bild-Auflistung-Sortieroptionen";
$GLOBALS['TL_LANG']['tl_content']['thumb_legend'] = "Thumbnail-Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['0'] = "Vorschaubilder pro Reihe";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['1'] = "W&auml;hlen Sie die Anzahl Vorschaubilder pro Reihe aus. (0=So viele wie m&ouml;glich)";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['0'] = "Lediglich folgende Alben im Frontend anzeigen";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['1'] = "Ausgew&auml;hlte Alben werden im Frontend angezeigt.";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_all_albums']['0'] = "Alle angelegten Alben im Frontend zeigen";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['0'] = "Galerietemplate";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['1'] = "Hier k&ouml;nnen Sie das Galerietemplate ausw&auml;hlen.";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['0'] = "Ajax-Thumb-Slider aktivieren";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['1'] = "Ajax-Thumb-Slider bei mouseover in der Alben&uuml;bersicht aktivieren?";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['0'] = "Weiterleitung bei einzelnem Album";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['1'] = "Soll, wenn nur ein Album ausgew&auml;hlt wurde, automatisch zur Detailansicht weitergeleitet weden?";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['0'] = "Anzahl Alben pro Seite in der Alben&uuml;bersicht";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['1'] = "Die Anzahl an Alben pro Seite in der Alben&uuml;bersicht. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['0'] = "Anzahl Bilder pro Seite in der Detailansicht";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['1'] = "Anzahl Bilder pro Seite in der Detailansicht. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['0'] = "Sortierung der Alben";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['1'] = "Nach welchem Feld sollen die Alben im Frontend sortiert werden?";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['0'] = "Sortierrichtung";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['1'] = "DESC: absteigend, ASC: aufsteigend";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting']['0'] = "Sortierung der Bilder";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting']['1'] = "Nach welchem Feld sollen die Bilder in einem einzelnen Album im Frontend sortiert werden?";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting_direction']['0'] = "Sortierrichtung";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting_direction']['1'] = "DESC: absteigend, ASC: aufsteigend";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['0'] = "Detailansicht: Thumbnailbreite und Thumbnailh&ouml;he";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['1'] = "Hier k&ouml;nnen Sie die Abmessungen des Bildes und den Skalierungsmodus festlegen.";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_detailview']['0'] = "Detailansicht: Bildabstand";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_detailview']['1'] =  "Hier können Sie den oberen, rechten, unteren und linken Bildabstand eingeben.";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['0'] = "Albumauflistung: Thumbnailbreite und Thumbnailh&ouml;he";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['1'] = "Hier k&ouml;nnen Sie die Abmessungen des Bildes und den Skalierungsmodus festlegen.";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_albumlisting']['0'] = "Albumauflistung: Bildabstand";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_albumlisting']['1'] = "Hier können Sie den oberen, rechten, unteren und linken Bildabstand eingeben.";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['0'] = "Großansicht/Neues Fenster";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['1'] = "Großansicht des Bildes in einer Lightbox bzw. den Link in einem neuem Browserfenster &ouml;ffnen.";
 
?>
