<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/tl_settings.php 
 * 
 * Contao extension: gallery_creator 4.1.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['gallery_creator_legend'] = "Gallery-Creator-Einstellungen";
$GLOBALS['TL_LANG']['tl_settings']['gc_watermark_opacity']['0'] = "Wasserzeichen-Opacity";
$GLOBALS['TL_LANG']['tl_settings']['gc_watermark_valign']['0'] = "Wasserzeichen: vertikale Position";
$GLOBALS['TL_LANG']['tl_settings']['gc_watermark_halign']['0'] = "Wasserzeichen: horizontale Position";
$GLOBALS['TL_LANG']['tl_settings']['gc_watermark_path']['0'] = "Wasserzeichen hinzuf&uuml;gen";
$GLOBALS['TL_LANG']['tl_settings']['gc_disable_backend_edit_protection']['0'] = "Backend-Album-Protection aufheben";
$GLOBALS['TL_LANG']['tl_settings']['gc_disable_backend_edit_protection']['1'] = "Backend-Album-Protection aufheben, damit auch Nichtbesitzer von Alben oder Bildern diese bearbeiten und l&ouml;schen k&ouml;nnen.";
$GLOBALS['TL_LANG']['tl_settings']['gc_album_import_copy_files']['0'] = "Beim Import von Bildern eine Kopie jeder Bilddatei im Verzeichnis \"tl_files/gallery_creator_albums\" erstellen";
$GLOBALS['TL_LANG']['tl_settings']['gc_album_import_copy_files']['1'] = "Wenn diese Einstellung gew&auml;hlt wird, erstellt contao beim Importieren von Bildern in ein Album automatisch eine Kopie im Verzeichnis \"tl_files/gallery_creator_albums\".";
